#!/bin/sh -l
# FILENAME:  run_py.sub

cd $PBS_O_WORKDIR
module load boost/1.49.0 cmake python swig atlas openmpi/1.6.3_gcc-4.7.2 hdf5/1.8.7_gcc-4.7.2
export HDF5_DIR=/apps/rhel6/hdf5/1.8.7_gcc-4.7.2
export LD_LIBRARY_PATH=/scratch/hansen/x/xie45/memosa/build-hansen-fvm/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/scratch/hansen/x/xie45/memosa/build-hansen-fvm/lib:/scratch/hansen/x/xie45/memosa/build-hansen-fvm/lib64/python2.7/site-packages:/scratch/hansen/x/xie45/memosa/build-hansen-fvm/lib/python2.7/site-packages:/scratch/hansen/x/xie45/memosa/build-hansen-fvm/bin:/apps/rhel6/Python-2.7.2/lib/python2.7/site-packages/grib_api
# Add include and lib directories to compiler paths
export C_INCLUDE_PATH=/scratch/hansen/x/xie45/memosa/build-hansen-fvm/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/scratch/hansen/x/xie45/memosa/build-hansen-fvm/include:$CPLUS_INCLUDE_PATH
export PATH=/scratch/hansen/x/xie45/memosa/build-hansen-fvm/bin:$PATH

# Need this to recompile MPM in its directory.
export MEMOSA_CONFNAME=hansen-fvm

pwd
mpirun -np 4 python ./SENT.py Miehe-2D.cas > SENT.out