#!/bin/sh -l
# FILENAME:  run_py.sub

cd $PBS_O_WORKDIR
module load devel
module load gcc
module load cmake swig atlas openmpi/1.8.1_gcc-4.7.2 hdf5/1.8.7_gcc-4.7.2
export HDF5_DIR=/apps/rhel6/hdf5/1.8.7_gcc-4.7.2
export PATH=/group/prism/apps/anaconda/bin:$PATH
export LD_LIBRARY_PATH=/scratch/conte/x/xie45/build-conte/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/scratch/conte/x/xie45/build-conte/lib:/scratch/conte/x/xie45/build-conte/lib64/python2.7/site-packages:/scratch/conte/x/xie45/build-conte/lib/python2.7/site-packages:/scratch/conte/x/xie45/build-conte/bin
# Add include and lib directories to compiler paths
export C_INCLUDE_PATH=/scratch/conte/x/xie45/build-conte/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/scratch/conte/x/xie45/build-conte/include:$CPLUS_INCLUDE_PATH
export PATH=/scratch/conte/x/xie45/build-conte/bin:$PATH

# Need this to recompile MPM in its directory.
export MEMOSA_CONFNAME=conte

pwd
mpirun -np 96 python ./multiFiber.py multifiber-2layers-3D-coarse.cas > multiFiber.out