#!/bin/sh -l
# FILENAME:  run_py.sub

cd $PBS_O_WORKDIR
module load cmake swig atlas openmpi/1.8.1_gcc-4.7.2 hdf5/1.8.7_gcc-4.7.2
export HDF5_DIR=/apps/rhel6/hdf5/1.8.7_gcc-4.7.2
export PATH=/group/prism/apps/anaconda/bin:$PATH
export LD_LIBRARY_PATH=/scratch/carter/x/xie45/memosa/build-carter/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/scratch/carter/x/xie45/memosa/build-carter/lib:/scratch/carter/x/xie45/memosa/build-carter/lib64/python2.7/site-packages:/scratch/carter/x/xie45/memosa/build-carter/lib/python2.7/site-packages:/scratch/carter/x/xie45/memosa/build-carter/bin
# Add include and lib directories to compiler paths
export C_INCLUDE_PATH=/scratch/carter/x/xie45/memosa/build-carter/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/scratch/carter/x/xie45/memosa/build-carter/include:$CPLUS_INCLUDE_PATH
export PATH=/scratch/carter/x/xie45/memosa/build-carter/bin:$PATH

# Need this to recompile MPM in its directory.
export MEMOSA_CONFNAME=carter

pwd
mpirun -np 2 python ./SENT.py lcrack-1mm-2D.cas > SENT.out